import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/app/components/ThemeProvider";
import Navbar from "@/app/components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <AuthProvider>
          <body className={inter.className}>
            <Navbar />
            {/* <ThemeProvider> */}
            {children}
            {/* </ThemeProvider> */}
          </body>
        </AuthProvider>
      </html>
    </>
  );
}
