import type { Metadata } from "next";
import type { Viewport } from 'next'
import { Inter } from "next/font/google";
import "./globals.css";
import MyThemeProvider from "./components/ThemeProvider";
import Navbar from "@/app/components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Document Translation System",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <AuthProvider>
          <body className={inter.className}>
            <Navbar />
            <MyThemeProvider>
              {children}
            </MyThemeProvider>
          </body>
        </AuthProvider>
      </html>
    </>
  );
}
