import type { Metadata } from 'next';
import type { Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MyThemeProvider from './components/ThemeProvider';
import Navbar from '@/app/components/Navbar';
import { AuthProvider } from './contexts/AuthContext';
import { LanguageProvider } from './contexts/LanguageContext';
import BackgroundWrapper from './components/BackgroundWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Document Translation System',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider>
          <AuthProvider>
            <MyThemeProvider>
              <BackgroundWrapper>
                <Navbar />
                <main style={{ minHeight: 'calc(100vh - 64px)' }}>
                  {' '}
                  {/* Adjust 64px to match your Navbar height */}
                  {children}
                </main>
              </BackgroundWrapper>
            </MyThemeProvider>
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
